on: [push, pull_request]

jobs:
  style:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup node
        uses: actions/setup-node@v4
        with:
          node-version: 18.19.0

      - name: Install dependencies
        run: npm ci

      - name: Check style
        run: npm run format:check
  test-unit:
    timeout-minutes: 15
    runs-on: ubuntu-latest
    container:
      image: cypress/browsers:node-18.16.0-chrome-114.0.5735.133-1-ff-114.0.2-edge-114.0.1823.51-1
      options: --user 1001
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup cypress
        uses: cypress-io/github-action@v6
        with:
          start: npm run dev
          runTests: false

      - name: Run unit tests
        run: npm run test:unit

  test-e2e:
    timeout-minutes: 15
    runs-on: ubuntu-latest
    container:
      image: cypress/browsers:node-18.16.0-chrome-114.0.5735.133-1-ff-114.0.2-edge-114.0.1823.51-1
      options: --user 1001
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Run e2e tests
        uses: cypress-io/github-action@v6
        with:
          start: npm run dev

        # - name: Upload coverage reports to Codecov
        #   uses: codecov/codecov-action@v3
        #   env:
        #     CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
