on: [push, pull_request]

env:
  AWS_REGION: eu-west-3

jobs:
  style:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup node
        uses: actions/setup-node@v4
        with:
          node-version: 18.19.0

      - name: Install dependencies
        run: npm ci

      - name: Check style
        run: npm run format:check

  test-unit:
    timeout-minutes: 15
    runs-on: ubuntu-latest
    container:
      image: cypress/browsers:node-18.16.0-chrome-114.0.5735.133-1-ff-114.0.2-edge-114.0.1823.51-1
      options: --user 1001
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup node
        uses: actions/setup-node@v4
        with:
          node-version: 18.19.0

      ## Connect to Poja Private Codeartifact Repository ##
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4.0.1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}
      - run: sh ./initNpmrc.sh jcloudify-store npm-jcloudify-app 057045785189

      - name: Setup cypress
        uses: cypress-io/github-action@v6
        with:
          runTests: false

      - name: Run unit tests
        run: npm run test:unit

  test-e2e:
    timeout-minutes: 15
    runs-on: ubuntu-latest
    container:
      image: cypress/browsers:node-18.16.0-chrome-114.0.5735.133-1-ff-114.0.2-edge-114.0.1823.51-1
      options: --user 1001
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup node
        uses: actions/setup-node@v4
        with:
          node-version: 18.19.0

      ## Connect to Poja Private Codeartifact Repository ##
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4.0.1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}
      - run: sh ./initNpmrc.sh jcloudify-store npm-jcloudify-app 057045785189

      - name: Run e2e tests
        uses: cypress-io/github-action@v6
        with:
          start: npm run dev

        # - name: Upload coverage reports to Codecov
        #   uses: codecov/codecov-action@v3
        #   env:
        #     CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
