name: E2E App Deployment

on: [workflow_dispatch]

env:
  AWS_REGION: eu-west-3
  REACT_APP_JCLOUDIFY_API_URL: ${{ vars.REACT_APP_JCLOUDIFY_API_URL }}

jobs:
  test-e2e:
    timeout-minutes: 15
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup node
        uses: actions/setup-node@v4
        with:
          node-version: 18.19.0

      ## Connect to Poja Private Codeartifact Repository ##
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4.0.1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - run: sh ./initNpmrc.sh jcloudify-store npm-jcloudify-app 057045785189

      - name: Run e2e tests
        uses: cypress-io/github-action@v6
        with:
          start: npm run dev
          spec: cypress/e2e/app_deployment_it/create_deployment.it.cy.ts
          record: true
        env:
          CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}
          CYPRESS_JCLOUDIFY_TEST_USER_TOKEN: ${{ secrets.CYPRESS_JCLOUDIFY_TEST_USER_TOKEN }}

      - name: Store Target App
        uses: actions/upload-artifact@v2
        with:
          name: target-app-id
          path: target-app-id.txt
